#!/bin/bash

# desktop::create get the system os
desktop::create() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[desktop::create] name is required"
    return 1
  fi

  zmicro template create desktop "$@"
}


export -f desktop::create
